In [2]:
import numpy as np

In [3]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [4]:
x = np.linspace(0,2*np.pi, 100)

In [5]:
np.cos(x)

array([ 1.        ,  0.99798668,  0.99195481,  0.9819287 ,  0.9679487 ,
        0.95007112,  0.92836793,  0.90292654,  0.87384938,  0.84125353,
        0.80527026,  0.76604444,  0.72373404,  0.67850941,  0.63055267,
        0.58005691,  0.52722547,  0.47227107,  0.41541501,  0.35688622,
        0.29692038,  0.23575894,  0.17364818,  0.1108382 ,  0.04758192,
       -0.01586596, -0.07924996, -0.14231484, -0.20480667, -0.26647381,
       -0.32706796, -0.38634513, -0.44406661, -0.5       , -0.55392006,
       -0.60560969, -0.65486073, -0.70147489, -0.74526445, -0.78605309,
       -0.82367658, -0.85798341, -0.88883545, -0.91610846, -0.93969262,
       -0.95949297, -0.97542979, -0.98743889, -0.99547192, -0.99949654,
       -0.99949654, -0.99547192, -0.98743889, -0.97542979, -0.95949297,
       -0.93969262, -0.91610846, -0.88883545, -0.85798341, -0.82367658,
       -0.78605309, -0.74526445, -0.70147489, -0.65486073, -0.60560969,
       -0.55392006, -0.5       , -0.44406661, -0.38634513, -0.32

In [6]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [7]:
# np.set_printoptions(threshold='nan')

In [8]:
print(x)

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [9]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [10]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [11]:
a = np.ones(3, dtype = np.int32)
b = np.linspace(0,np.pi, 3)
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [12]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [13]:
d.dtype.name

'complex128'

In [14]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
b.sum()

66

In [16]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [17]:
b.sum(axis=1)

array([ 6, 22, 38])

In [18]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [19]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [20]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [21]:
b = np.arange(3)
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [22]:
b

array([0, 1, 2])

In [23]:
c = np.array([2., -1., 4.])
c

array([ 2., -1.,  4.])

In [24]:
d = np.add(b,c)
d

array([ 2.,  0.,  6.])

In [25]:
d.dtype

dtype('float64')

In [26]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [28]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a = a ** 3
a[2]

8

In [30]:
a[2:5]

array([ 8, 27, 64])

In [31]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [32]:
a[: : -1]  #reverse a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [33]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [34]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/yuepan/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [35]:
def f(x,y):
    return 10*x + y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [36]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [37]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [38]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [39]:
b[-1]   # the last row,equivalent to b[-1,:]

array([40, 41, 42, 43])

In [40]:
#The dots (...) represent as many colons as needed to produce a complete indexing tuple.
#For example, if x is a rank 5 array (i.e., it has 5 axes), then
c = np.array([[[0,1,2],[10,11,12]], [[100,101,102],[110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [41]:
c.shape

(2, 2, 3)

In [42]:
c[1,...]   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [43]:
c[...,2]    # same as c[:,:,2]

array([[  2,  12],
       [102, 113]])

In [44]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [45]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [46]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [47]:
a = np.floor(10*np.random.random([3,4]))
a

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [48]:
a.shape

(3, 4)

In [49]:
a.ravel()

array([ 2.,  2.,  8.,  4.,  3.,  6.,  2.,  4.,  6.,  6.,  2.,  3.])

In [50]:
a

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [51]:
a.reshape(6,2) #reshape function returns its argument with a modified shape, 

array([[ 2.,  2.],
       [ 8.,  4.],
       [ 3.,  6.],
       [ 2.,  4.],
       [ 6.,  6.],
       [ 2.,  3.]])

In [52]:
a

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [53]:
a.T   #return the array, transposed

array([[ 2.,  3.,  6.],
       [ 2.,  6.,  6.],
       [ 8.,  2.,  2.],
       [ 4.,  4.,  3.]])

In [54]:
a

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [55]:
a.resize(2,6)  #unlike reshape, resize method modify the ndarray itself

In [56]:
a

array([[ 2.,  2.,  8.,  4.,  3.,  6.],
       [ 2.,  4.,  6.,  6.,  2.,  3.]])

In [57]:
a.reshape(3,-1)  #if a dimension is given as -1, it will be automatically calculated

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [58]:
a.reshape(3,4)

array([[ 2.,  2.,  8.,  4.],
       [ 3.,  6.,  2.,  4.],
       [ 6.,  6.,  2.,  3.]])

In [59]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
b = a  #simple assignments make no copy of array objects or of their data

In [61]:
b is a

True

In [62]:
b.shape = 3,4

In [63]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a.shape

(3, 4)

In [65]:
id(a)

4535759216

In [66]:
id(b)    #id is a unique identifier of an object

4535759216

In [67]:
c = a.view()   #c is a view of the data owned by a

In [68]:
c is a

False

In [69]:
c.shape = 2,6

In [70]:
a.shape

(3, 4)

In [71]:
c.flags
c.flags.owndata

False

In [72]:
c[0,4] = 1234
a    #a's shape doesn't change, but a's data changes

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [73]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [74]:
d = a.copy()    # a new array object with new data is created
d is a 

False

In [75]:
d.base is a    #d doesn't share anything with a

False

In [76]:
d

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [77]:
d[0,0] = 9999
d

array([[9999,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [78]:
a    #a doesn't change when d changes

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [79]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [80]:
i = np.array([1,1,3,8,5])
i

array([1, 1, 3, 8, 5])

In [81]:
a[i]   #the elements of a at the positions i

array([ 1,  1,  9, 64, 25])

In [82]:
j = np.array([[3,4],[9,7]])
j       # a bidimensional array of indices

array([[3, 4],
       [9, 7]])

In [83]:
a[j]   # the same shape as j

array([[ 9, 16],
       [81, 49]])

In [84]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
i = np.array([[0,1],[1,2]])
i

array([[0, 1],
       [1, 2]])

In [86]:
j = np.array([[2,1],[3,3]])
j

array([[2, 1],
       [3, 3]])

In [87]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [88]:
a[i,j]    #i and j must have equal shape

array([[ 2,  5],
       [ 7, 11]])

In [89]:
l = [i, j]
l

[array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 3]])]

In [90]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [91]:
s = np.array([i,j])
s

array([[[0, 1],
        [1, 2]],

       [[2, 1],
        [3, 3]]])

In [92]:
a[s]   
# we cannot do this by putting i and j into an array, 
#because this array with be interpreted as indexing the first dimension of a

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
a[tuple(s)]   #as as a[i,j]

In [ ]:
time = np.linspace(20, 145, 5)
time

In [ ]:
data = np.sin(np.arange(20)).reshape(5,4)
data

In [ ]:
ind = data.argmax(axis=0)
ind

In [ ]:
time_max  = time[ind]
time_max

In [ ]:
data_max = data[ind, np.arange(data.shape[1])] # data[ind[0],0], data[ind[1],1],....
data_max
# data.shape[1]

In [ ]:
data.shape

In [ ]:
data.shape[1]  #data.shape[1] return the size of the second dimension

In [ ]:
data[ind, 0:4]

In [ ]:
data[ind, np.array([0,1,2,3])]   # same as data[ind, np.arange(data.shape[1])]

In [96]:
np.random.randint(0,9,(4,2))

array([[6, 0],
       [2, 4],
       [3, 7],
       [2, 4]])

In [100]:
s = np.random.randint(-5,10,9)
s

array([ 8,  6, -1,  8, -3, -4,  1,  2,  0])

In [101]:
s.cumsum()

array([ 8, 14, 13, 21, 18, 14, 15, 17, 17])