In [1]:
import pandas as pd
import numpy as np

In [5]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


# Your answer here


In [6]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [7]:
x = np.linspace(0,2*np.pi, 100)

In [8]:
np.cos(x)

array([ 1.        ,  0.99798668,  0.99195481,  0.9819287 ,  0.9679487 ,
        0.95007112,  0.92836793,  0.90292654,  0.87384938,  0.84125353,
        0.80527026,  0.76604444,  0.72373404,  0.67850941,  0.63055267,
        0.58005691,  0.52722547,  0.47227107,  0.41541501,  0.35688622,
        0.29692038,  0.23575894,  0.17364818,  0.1108382 ,  0.04758192,
       -0.01586596, -0.07924996, -0.14231484, -0.20480667, -0.26647381,
       -0.32706796, -0.38634513, -0.44406661, -0.5       , -0.55392006,
       -0.60560969, -0.65486073, -0.70147489, -0.74526445, -0.78605309,
       -0.82367658, -0.85798341, -0.88883545, -0.91610846, -0.93969262,
       -0.95949297, -0.97542979, -0.98743889, -0.99547192, -0.99949654,
       -0.99949654, -0.99547192, -0.98743889, -0.97542979, -0.95949297,
       -0.93969262, -0.91610846, -0.88883545, -0.85798341, -0.82367658,
       -0.78605309, -0.74526445, -0.70147489, -0.65486073, -0.60560969,
       -0.55392006, -0.5       , -0.44406661, -0.38634513, -0.32

In [9]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [10]:
# np.set_printoptions(threshold='nan')

In [11]:
print(x)

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [12]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [13]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
a = np.ones(3, dtype = np.int32)
b = np.linspace(0,np.pi, 3)
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [16]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [18]:
d.dtype.name

'complex128'

In [19]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b.sum()

66

In [21]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [22]:
b.sum(axis=1)

array([ 6, 22, 38])

In [23]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [24]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [25]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [26]:
b = np.arange(3)
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [27]:
b

array([0, 1, 2])

In [30]:
c = np.array([2., -1., 4.])
c

array([ 2., -1.,  4.])

In [32]:
d = np.add(b,c)
d

array([ 2.,  0.,  6.])

In [35]:
d.dtype

dtype('float64')

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = a ** 3
a[2]

8

In [42]:
a[2:5]

array([ 8, 27, 64])

In [43]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [44]:
a[: : -1]  #reverse a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [45]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [46]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/yuepan/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [47]:
def f(x,y):
    return 10*x + y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [48]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [49]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [50]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [51]:
b[-1]   # the last row,equivalent to b[-1,:]

array([40, 41, 42, 43])

In [53]:
#The dots (...) represent as many colons as needed to produce a complete indexing tuple.
#For example, if x is a rank 5 array (i.e., it has 5 axes), then
c = np.array([[[0,1,2],[10,11,12]], [[100,101,102],[110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [54]:
c.shape

(2, 2, 3)

In [57]:
c[1,...]   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [58]:
c[...,2]    # same as c[:,:,2]

array([[  2,  12],
       [102, 113]])

In [59]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [60]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [61]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
